# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.5.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGraphicsView, QGroupBox, QHBoxLayout,
    QLabel, QListView, QMainWindow, QMenuBar,
    QPushButton, QSizePolicy, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1019, 509)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.canva = QGraphicsView(self.centralwidget)
        self.canva.setObjectName(u"canva")
        self.canva.setGeometry(QRect(10, 10, 791, 441))
        self.canva.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.canva.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        brush = QBrush(QColor(0, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        self.canva.setBackgroundBrush(brush)
        self.card_selector = QListView(self.centralwidget)
        self.card_selector.setObjectName(u"card_selector")
        self.card_selector.setGeometry(QRect(810, 100, 201, 311))
        self.card_selector.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.card_selector.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.card_selector.setBatchSize(100)
        self.cannot_play_msg = QLabel(self.centralwidget)
        self.cannot_play_msg.setObjectName(u"cannot_play_msg")
        self.cannot_play_msg.setGeometry(QRect(860, 420, 111, 16))
        self.cannot_play_msg.setStyleSheet(u"QLabel{color:#f00}")
        self.horizontalLayoutWidget = QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(808, 440, 201, 41))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.pass_ = QPushButton(self.horizontalLayoutWidget)
        self.pass_.setObjectName(u"pass_")
        self.pass_.setEnabled(False)
        self.pass_.setCheckable(False)

        self.horizontalLayout.addWidget(self.pass_)

        self.submit = QPushButton(self.horizontalLayoutWidget)
        self.submit.setObjectName(u"submit")
        self.submit.setEnabled(False)
        self.submit.setCheckable(False)

        self.horizontalLayout.addWidget(self.submit)

        self.rule29 = QLabel(self.centralwidget)
        self.rule29.setObjectName(u"rule29")
        self.rule29.setGeometry(QRect(140, 460, 51, 21))
        font = QFont()
        font.setPointSize(12)
        self.rule29.setFont(font)
        self.rule29.setStyleSheet(u"QLabel{color:#f00}")
        self.rule19 = QLabel(self.centralwidget)
        self.rule19.setObjectName(u"rule19")
        self.rule19.setGeometry(QRect(80, 460, 51, 21))
        self.rule19.setFont(font)
        self.rule19.setStyleSheet(u"QLabel{color:#f00}")
        self.rule9 = QLabel(self.centralwidget)
        self.rule9.setObjectName(u"rule9")
        self.rule9.setGeometry(QRect(20, 460, 51, 21))
        self.rule9.setFont(font)
        self.rule9.setStyleSheet(u"QLabel{color:#f00}")
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(810, 10, 201, 81))
        self.horizontalLayoutWidget_2 = QWidget(self.groupBox)
        self.horizontalLayoutWidget_2.setObjectName(u"horizontalLayoutWidget_2")
        self.horizontalLayoutWidget_2.setGeometry(QRect(0, 20, 201, 61))
        self.prev_hand = QHBoxLayout(self.horizontalLayoutWidget_2)
        self.prev_hand.setObjectName(u"prev_hand")
        self.prev_hand.setContentsMargins(0, 0, 0, 0)
        self.player1_icon = QLabel(self.centralwidget)
        self.player1_icon.setObjectName(u"player1_icon")
        self.player1_icon.setGeometry(QRect(20, 190, 71, 71))
        font1 = QFont()
        font1.setPointSize(36)
        self.player1_icon.setFont(font1)
        self.player1_icon.setStyleSheet(u"border: 1px solid black; border-radius: 10px;background-color: #ff0")
        self.player1_icon.setAlignment(Qt.AlignCenter)
        self.player1_name = QLabel(self.centralwidget)
        self.player1_name.setObjectName(u"player1_name")
        self.player1_name.setGeometry(QRect(20, 260, 71, 21))
        self.player1_name.setFont(font)
        self.player1_name.setAlignment(Qt.AlignCenter)
        self.player1_hand_count = QLabel(self.centralwidget)
        self.player1_hand_count.setObjectName(u"player1_hand_count")
        self.player1_hand_count.setGeometry(QRect(30, 140, 53, 41))
        font2 = QFont()
        font2.setPointSize(28)
        self.player1_hand_count.setFont(font2)
        self.player1_hand_count.setAlignment(Qt.AlignCenter)
        self.player2_icon = QLabel(self.centralwidget)
        self.player2_icon.setObjectName(u"player2_icon")
        self.player2_icon.setGeometry(QRect(370, 20, 71, 71))
        self.player2_icon.setFont(font1)
        self.player2_icon.setStyleSheet(u"QLabel{border: 1px solid black; border-radius: 10px;background-color: #ff0}")
        self.player2_icon.setAlignment(Qt.AlignCenter)
        self.player2_name = QLabel(self.centralwidget)
        self.player2_name.setObjectName(u"player2_name")
        self.player2_name.setGeometry(QRect(450, 70, 71, 21))
        self.player2_name.setFont(font)
        self.player2_name.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.player2_hand_count = QLabel(self.centralwidget)
        self.player2_hand_count.setObjectName(u"player2_hand_count")
        self.player2_hand_count.setGeometry(QRect(310, 30, 53, 41))
        self.player2_hand_count.setFont(font2)
        self.player2_hand_count.setAlignment(Qt.AlignCenter)
        self.player3_hand_count = QLabel(self.centralwidget)
        self.player3_hand_count.setObjectName(u"player3_hand_count")
        self.player3_hand_count.setGeometry(QRect(730, 140, 53, 41))
        self.player3_hand_count.setFont(font2)
        self.player3_hand_count.setAlignment(Qt.AlignCenter)
        self.player3_icon = QLabel(self.centralwidget)
        self.player3_icon.setObjectName(u"player3_icon")
        self.player3_icon.setGeometry(QRect(720, 190, 71, 71))
        self.player3_icon.setFont(font1)
        self.player3_icon.setStyleSheet(u"QLabel{border: 1px solid black; border-radius: 10px;background-color: #ff0}")
        self.player3_icon.setAlignment(Qt.AlignCenter)
        self.player3_name = QLabel(self.centralwidget)
        self.player3_name.setObjectName(u"player3_name")
        self.player3_name.setGeometry(QRect(720, 260, 71, 21))
        self.player3_name.setFont(font)
        self.player3_name.setAlignment(Qt.AlignCenter)
        self.player0_name = QLabel(self.centralwidget)
        self.player0_name.setObjectName(u"player0_name")
        self.player0_name.setGeometry(QRect(90, 420, 71, 21))
        self.player0_name.setFont(font)
        self.player0_name.setAlignment(Qt.AlignCenter)
        self.player0_icon = QLabel(self.centralwidget)
        self.player0_icon.setObjectName(u"player0_icon")
        self.player0_icon.setGeometry(QRect(20, 370, 71, 71))
        self.player0_icon.setFont(font1)
        self.player0_icon.setStyleSheet(u"QLabel{border: 1px solid black; border-radius: 10px;background-color: #ff0}")
        self.player0_icon.setAlignment(Qt.AlignCenter)
        self.player0_hand_count = QLabel(self.centralwidget)
        self.player0_hand_count.setObjectName(u"player0_hand_count")
        self.player0_hand_count.setGeometry(QRect(100, 370, 53, 41))
        self.player0_hand_count.setFont(font2)
        self.player0_hand_count.setAlignment(Qt.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1019, 22))
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.cannot_play_msg.setText(QCoreApplication.translate("MainWindow", u"\u8acb\u5148\u9078\u8981\u6253\u51fa\u7684\u724c!", None))
        self.pass_.setText(QCoreApplication.translate("MainWindow", u"Pass", None))
        self.submit.setText(QCoreApplication.translate("MainWindow", u"\u6253\u51fa", None))
        self.rule29.setText(QCoreApplication.translate("MainWindow", u"3\u58d31\u2718", None))
        self.rule19.setText(QCoreApplication.translate("MainWindow", u"3\u58d32\u2718", None))
        self.rule9.setText(QCoreApplication.translate("MainWindow", u"2\u58d31\u2718", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"\u524d\u7d44\u724c\u578b", None))
        self.player1_icon.setText(QCoreApplication.translate("MainWindow", u"\u9673", None))
        self.player1_name.setText(QCoreApplication.translate("MainWindow", u"\u9673\u4f91\u6fa4", None))
        self.player1_hand_count.setText(QCoreApplication.translate("MainWindow", u"10", None))
        self.player2_icon.setText(QCoreApplication.translate("MainWindow", u"\u9673", None))
        self.player2_name.setText(QCoreApplication.translate("MainWindow", u"\u9673\u4f91\u6fa4", None))
        self.player2_hand_count.setText(QCoreApplication.translate("MainWindow", u"10", None))
        self.player3_hand_count.setText(QCoreApplication.translate("MainWindow", u"10", None))
        self.player3_icon.setText(QCoreApplication.translate("MainWindow", u"\u9673", None))
        self.player3_name.setText(QCoreApplication.translate("MainWindow", u"\u9673\u4f91\u6fa4", None))
        self.player0_name.setText(QCoreApplication.translate("MainWindow", u"\u9673\u4f91\u6fa4", None))
        self.player0_icon.setText(QCoreApplication.translate("MainWindow", u"\u9673", None))
        self.player0_hand_count.setText(QCoreApplication.translate("MainWindow", u"10", None))
    # retranslateUi

